[versions]
compose-bom = "2023.06.01"
core = "1.9.0"
lifecycle = "2.6.1"
activity = "1.7.2"
junit = "4.13.2"
androidx-junit = "1.1.5"
espresso = "3.5.1"
navigation = "2.5.3"
# @pin - Be sure to use compatible version that is supported by compose compiler https://developer.android.com/jetpack/androidx/releases/compose-kotlin
kotlin = "1.8.21"
androidGradlePlugin = "8.0.2"
gradleVersionsPlugin = "0.47.0"
littleRobotsVersionCatalog = "0.8.0"

[libraries]
# Compose
composeBom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
composeUi = { module = "androidx.compose.ui:ui" }
composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
composeUiTooling = { module = "androidx.compose.ui:ui-tooling" }
composeMaterial3 = { module = "androidx.compose.material3:material3" }
composeUiTestJunit4 = { module = "androidx.compose.ui:ui-test-junit4" }
composeUiTestManifest = { module = "androidx.compose.ui:ui-test-manifest" }
composeActivity = { module = "androidx.activity:activity-compose", version.ref = "activity" }

# Androidx
androidxCore = { module = "androidx.core:core-ktx", version.ref = "core" }
androidxActivity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }

# Lifecycle
lifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }

# Navigation
navigationCompose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

# Test
junit = { module = "junit:junit", version.ref = "junit" }
androidxJunit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

[bundles]
compose = [
    "composeUi",
    "composeUiToolingPreview",
    "composeMaterial3",
    "composeActivity",
]

composeTest = [
    "composeUiTestJunit4",
]

composeDebug = [
    "composeUiTooling",
    "composeUiTestManifest",
]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
gradleVersions = { id = "com.github.ben-manes.versions", version.ref = "gradleVersionsPlugin" }
littleRobotsVersionCatalog = { id = "nl.littlerobots.version-catalog-update", version.ref = "littleRobotsVersionCatalog" }
