name: Create Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to create release from'
        required: true
      tag:
        description: 'Tag name'
        required: true
      tag_previous:
        description: 'Previous tag name'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

      - name: Create tag
        run: |
          git fetch --all --tags
          git checkout ${{ github.event.inputs.branch }}
          git tag ${{ github.event.inputs.tag }}
          git push origin ${{ github.event.inputs.tag }}

      - name: Generate release notes
        id: generate_release_notes
        run: |
          IFS=$'\n'
          output=""
          for line in $(git log --oneline ${{ github.event.inputs.tag_previous }}..${{ github.event.inputs.tag }}); do
          echo "Processing line: $line"
          line="${line//'%'/'%25'}"
          line="${line//$'\n'/'%0A'}"
          line="${line//$'\r'/'%0D'}"
          output+="$line%0A"
          done
          echo "::set-output name=notes::${output}"
          echo "Final output: $output"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: Release ${{ github.event.inputs.tag }}
          body: ${{ steps.generate_release_notes.outputs.notes }}
          draft: false
          prerelease: false
