name: Create Tag and Release

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to tag'
        required: true
      tag_new:
        description: 'The new tag'
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

      - name: Create tag
        run: |
          git checkout ${{ github.event.inputs.branch }}
          git tag ${{ github.event.inputs.tag_new }}
          git push origin ${{ github.event.inputs.tag_new }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Get previous tag
        id: prev_tag
        run: |
          echo "::set-output name=tag::$(git describe --tags --abbrev=0 ${GITHUB_REF}~)"
        
      - name: Create Release notes
        id: create_release_notes
        run: |
          PR_LIST=$(git log --merges --pretty="%b" ${{ steps.prev_tag.outputs.tag }}..${{ github.event.inputs.tag_new }} | grep 'pull request' | awk '{print $4}' | awk -F"/" '{print $NF}')
          RELEASE_BODY=""
          for pr_num in $PR_LIST
          do
            if [[ ! -z "$pr_num" && "$pr_num" =~ ^[0-9]+$ ]]; then
              PR_DATA=$(gh pr view $pr_num --json title,url,number -q '.number + " " + .title + " " + .url')
              RELEASE_BODY+="- PR#${PR_DATA}\n"
            fi
          done
          echo "RELEASE_BODY=${RELEASE_BODY}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_new }}
          release_name: Release ${{ github.event.inputs.tag_new }}
          body: ${{ env.RELEASE_BODY }}
