name: Create Release and Generate Notes
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to create a release from'
        required: true
      new_tag:
        description: 'The new tag'
        required: true

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

      - name: Create tag
        run: |
          git checkout ${{ github.event.inputs.branch }}
          git tag ${{ github.event.inputs.new_tag }}
          git push origin ${{ github.event.inputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}

      - name: Generate Release Notes
        run: |
          PR_LIST=$(gh pr list --base ${{ github.event.inputs.branch }} --json number,title,url,state --jq '.[] | select(.state=="MERGED") | "- [#\(.number)](\(.url)) \(.title)"')
          echo "RELEASE_NOTES=$PR_LIST" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
      - name: Debug Release Notes
        run: |
          echo $RELEASE_NOTES
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.new_tag }}
          release_name: Release ${{ github.event.inputs.new_tag }}
          body: ${{ env.RELEASE_NOTES }}
