name: Manage Renovate pull requests

on:
  workflow_dispatch:
    inputs:
      job_name:
        description: 'A job name'
        required: true
        type: choice
        options:
          - execute-renovate

run-name: "Manage Renovate PRs by ${{ github.actor }} - ${{ github.event_name }}"

permissions: {}

jobs:
  # Test job for renovate configurations.
  # You have to set your PAT to secrets.
  execute-renovate:
    if: >
      inputs.job_name == 'execute-renovate'

    timeout-minutes: 5

    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@5e224f3a02c7ce9cadc83f82d65f1b6dd73876c1 # v39.0.3
        with:
          configurationFile: renovate.json5
          token: ${{ secrets.RENOVATE_TEST_TOKEN }} # workflow, repo, read user:email permissions
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_REPOSITORIES: ${{ github.repository }}