name: Manage Renovate pull requests

on:
  workflow_dispatch:
    inputs:
      job_name:
        description: 'A job name'
        required: true
        type: choice
        options:
          - execute-renovate

run-name: "Manage Renovate PRs by ${{ github.actor }} - ${{ github.event_name }}"

permissions: {}

jobs:
  # Test job for renovate configurations.
  # You have to set your PAT to secrets.
  execute-renovate:
    if: >
      inputs.job_name == 'execute-renovate'

    timeout-minutes: 5

    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@3cef36a9aba515d8726b491905b3bc766832e221 # v39.0.5
        with:
          configurationFile: renovate.json5
          token: ${{ secrets.RENOVATE_TEST_TOKEN }} # workflow, repo, read user:email permissions
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_REPOSITORIES: ${{ github.repository }}